### ISSUE TITLE
Items not showing drop/sell locations

### ISSUE THREAD

**Issue by raidaddicts** [Akkadius/EQEmuAllakhazamClone#1]
When you do an item search and click onto an item it does not show you where the item drops or is sold.

For instance: http://raidaddicts.org/Allah/?a=item&id=35170

Should show a mob in Anguish

**Comment by Akkadius** [comment]
Fixed in commit: https://github.com/Akkadius/EQEmuAllakhazamClone/commit/2ffeb2edfb7193756330c08a902e47eb86d895a7
