### ISSUE TITLE
Some stuff not showing up

### ISSUE THREAD

**Issue by raidaddicts** [Akkadius/EQEmuAllakhazamClone#5]
OK so , i had some players do some test runs with the new Allah last night and today, one thing I have noticed is certain items will show up but the mobs won't, which also makes it so they don't show where they drop. 

For instance : http://www.raidaddicts.org/Allah/?a=global_search&q=Avatar%20of%20War

The mob exists , but doesn't show up in Allah , also if you take one of his drops say:  http://www.raidaddicts.org/Allah/?a=item&id=34468

It will not show who drops it, the first thing I did notice however about this mob when I pull him up on my PEQ editor on the server it shows as this : "The_Avatar_of_War - ()"  , so inbetween the () would normally be like a zone , however for some reason he is blank, i noticed over the last few years I have many encounters like that, stuff that I had one place but then moved..  Is this something that you can fix on the Allah clone or is this something that needs to be fixed in my database?  

Appreciate your time and work as always

Mortaaaayyyyyyyyyyyyhoe

**Comment by Akkadius** [comment]
Fixed in:

https://github.com/Akkadius/EQEmuAllakhazamClone/commit/79d2ffcbf87c2a2805b013ddef0e2c707ec63b9a
